### ISSUE TITLE
Implement 64-bit uint

### ISSUE THREAD

**Issue by maddouri** [vtereshkov/umka-lang#15]
Hello!

According to the documentation (and [umka_types.c](https://github.com/vtereshkov/umka-lang/blob/b8c2ac1994c515621e6ecd8a3b8d3dbd84784dcc/src/umka_types.c#L10)), Umka has the following built-in types:

```
void
int8 int16 int32 int
uint8 uint16 uint32
bool
char
real32 real
fiber
```

In order to give users more choice/flexibility and achieve better compatibility with C and C++ code (when using Umka as an embedded/extension language) I would like to suggest taking inspiration from other languages and consider the following:

1. Adding `int64` and `uint64`
1. Renaming `real*` to `float*`
1. Adding `float64`
1. Adding `ssize` (or `isize`) and `usize` (equivalent of [C](https://en.wikipedia.org/wiki/C_data_types#Size_and_pointer_difference_types)'s `ssize_t` and `size_t`, or [Rust](https://doc.rust-lang.org/book/ch03-02-data-types.html)'s `isize` and `usize`)
1. Adding `c_(u)short`, `c_(u)int` etc. (perhaps with better names 😉) and mapping them to [C](https://en.wikipedia.org/wiki/C_data_types#Main_types)'s `(unsigned) short`, `(unsigned) int`, etc. (like [Zig](https://ziglang.org/documentation/0.6.0/#Primitive-Types))

Thank you for starting this interesting project as well as considering the above suggestions 😊

**Comment by vtereshkov** [comment]
@maddouri My idea was to keep the type system as simple as possible. After all, Umka is a language for scripting, not for systems programming. That's why I avoid type aliases. If I have 64-bit `int` and `real`, I don't introduce `int64` and `real64`. The 64-bit representation is natural for Umka irrespective of the platform, so the 64-bit type names don't have the suffix. This encourages using them "by default". What Umka is really lacking now is `uint` (or `uint64`), since it would complicate the virtual machine.

As for the naming of real types, I think that `real` better reflects the purpose of these types than `float` (one needs a real number and doesn't care of whether its decimal point is floating or not in its hardware representation).

**Comment by maddouri** [comment]
I'm not sure that I agree with your premise (i.e. "more type choice" being at odds with "simplicity of the type system").

That being said, while I mentioned points 4 and 5 in order to have better type parity with C (in case one were to call C functions or exchange data that use those types) I am not particularly attached to them.

Regarding floats, I am under the impression that floating point representation is widespread enough (i.e. used by most languages I am aware of, including general purpose languages like [Go](https://tour.golang.org/basics/11) and scientific ones like [Julia](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/)) to equate it with the notion of real numbers when developing software (unless another particular representation is needed for some reason). Therefore, I thought it would be more intuitive to use the same name as in most mainstream programming languages.

Hopefully you can at least add uint64 in the future.

**Comment by vktec** [comment]
I don't think using the same type names as other languages should be a priority. It's better to have clearer type names that take a little longer to get used to.

For example, `int` in Go is (at least) 32 bits, but the only reason for it to be this size is because C's int is 32 bits in most implementations so it's more familiar to C programmers. On 64-bit systems it makes much more sense to have the `int` type be 64 bits.

To me, the name `float` is often synonymous with "real number rounded to a certain precision", but that's only because I'm used to the type of those numbers being called `float`. To a new programmer, the name `real` makes a lot more sense, and is more consistent with `int`.
