### ISSUE TITLE
raylib + LoadTexture

### ISSUE THREAD

**Issue by RobLoach** [vtereshkov/umka-lang#221]
Hey @vtereshkov... Saw you put together some small raylib examples, and I kind of built off of your idea here with [raylib-umka](https://github.com/robloach/raylib-umka), with a goal of supporting the entire raylib API through Umka :rocket: 

Ran into an issue though with `Texture LoadTexture(const char* fileName)`...

``` c
void umkaLoadTexture(UmkaStackSlot *params, UmkaStackSlot *result) {
    // TODO: Why does this need to be 1 instead of 0? Definition is...
    //     LoadTexture(fileName: str) : Texture
    const char * fileName = (const char *)params[1].ptrVal;
    TraceLog(LOG_INFO, "Loading: %s", fileName);
    result->ptrVal = umkaAllocData(result->ptrVal, sizeof(Texture2D), NULL);
    Texture2D out = LoadTexture(fileName);
    RAYLIB_UMKA_MEMCPY(result->ptrVal, &out, sizeof(Texture2D));
}
```

One would expect it to be `params[0].ptrVal` since `fileName` is the only parameter for the function. Do you know if I'm doing something wrong? I've created a Pull Request to demonstrate the change over at https://github.com/RobLoach/raylib-umka/pull/10 .

``` c
    // LoadTexture()
    if (!umkaAddFunc(umka, "LoadTexture", &umkaLoadTexture)) {
        TraceLog(LOG_ERROR, "UMKA: Failed to add function LoadTexture()");
        return false;
    }
```

``` umka
fn LoadTexture*(fileName: str): Texture

Texture* = struct {
  id: uint32
  width: int32
  height: int32
  mipmaps: int32
  format: int32
}
```

**Comment by marekmaskarinec** [comment]
If you return a structure larger than one stack slot, it will overlap into the parameters. I recommend passing a return pointer for larger structures.

**Comment by vtereshkov** [comment]
@RobLoach A function that returns a structured result always has a hidden last parameter (a pointer to where the result should be stored in the caller). So this hidden parameter will be `params[0]` and the file name will be `params[1]`. You should also save the pointer from this hidden parameter into `result`.

However, your code seems to be assuming that you allocate the memory for the returned value in the callee, not the caller. Then you should return `^Texture` instead of `Texture` and forget about the hidden parameter.

**Comment by RobLoach** [comment]
Thanks so much for the help! That fixed it.  I've created a follow up issue to switch the API to return pointers like `^Texture` instead https://github.com/RobLoach/raylib-umka/issues/12 . Raylib expects full objects, so I'll need to do some thinking on that one.
