### ISSUE TITLE
Can not load relative modules in emscripten

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#269]
![image](https://user-images.githubusercontent.com/27076041/224481542-6d5bbaf1-c9cb-4d42-9a30-0dac91414743.png)

The last 4 lines are the most important.
Here we can see it checks module at `/src/editor/../d_util.um`, fails to load, then tries to load `/../d_util.um` (I assume it's a fallback to absolute path).

**Comment by skejeton** [comment]
![image](https://user-images.githubusercontent.com/27076041/224486271-2135e4af-329a-4166-9752-de87cd988c0b.png)
more info: the path normalizer seems to work as intended, so it looks like emscripten can't locate file at `/src/d_util.um"? interesting

**Comment by skejeton** [comment]
I will try a newer version of emscripten

**Comment by RobLoach** [comment]
I'm assuming you also mounted the filesystem using `--preload-file`?

**Comment by skejeton** [comment]
yes

**Comment by vtereshkov** [comment]
@skejeton @marekmaskarinec My current understanding is that the problem is threefold:

1. The `getcwd()` function returns the root folder under Emscripten.
2. If an `import` clause refers to an embedded module, the specified file path is treated with respect to the folder Umka was run from (i.e., the root folder under Emscripten). This is generally the intended behavior, since, for example, we want to import the standard library just as `std.um` from any module, rather than `../../../std.um`, etc. So, in @marekmaskarinec 's case, the recommended solution for now is exactly what he has done, i. e., to replace `../ui.um` with `ui.um`.
3. If an `import` clause refers to a physical file, the specified file path is treated with respect to the current module's folder. However, Umka tried first to build a path as for an embedded module. A failure to do so was treated as a fatal error without even trying to build a path as for a physical file. This seems to be @skejeton 's case. It could be reproduced even without Emscripten:
```
// c:\umka\test\test\test.um
import "../../lib.um"
fn main() {
	lib.do(5)
}
```
```
// c:\umka\lib.um
fn do*(x: int) {
	printf(repr(x) + '\n')
}
```
```
C:\umka_windows_mingw>umka.exe test\test\test.um
Error C:/umka/test/test/test.um (1, 8): Invalid module path ../../lib.um
```
Now this behavior is fixed. @skejeton please test it.
