### ISSUE TITLE
Ternary operators

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#287]
Ternary operators allow to do `if` as expressions. For example:
```go
fn max(a, b: int) {
  return a < b ? b : a
}
```

They can be useful in a lot of small inline cases, like shown above. 
In go they're debated especially for nested cases, whether nesting should be allowed or not is debatable, since once it's implemented as an expression, nesting is allowed unless a specific check is implemented against it. 

They can also be optimized easier, for example, since function above only has one return: it might be reasonable to optimize it by inlining the return instruction, which I assume would be harder to do if it was a multi-line if function.

**Comment by skejeton** [comment]
The syntax is up to choice here, we could do something like this, gdscript inspired:
```go
fn max(a, b: int) {
  return b if a < b else a
}
```
(notice the check expression is now in the middle)

**Comment by vtereshkov** [comment]
I like this proposal. As for the syntax, I think that `b if a < b else a` is very hard to compile for a single-pass compiler that generates  bytecode on-the-fly. The compiler sees `b` but does not know whether to insert a jump instruction before it to skip this `b` if `a < b` yields `false`.

**Comment by marekmaskarinec** [comment]
I would like ternary operators in umka. There are a lot of cases where they would be useful. As for the syntax proposed by @vtereshkov, I think it would imply that switch statement s and maybe even loops support this syntax too. Something to think about?

**Comment by vtereshkov** [comment]
There is an unexpected issue with reference counting that we need to solve before we can implement the ternary operator. Consider the following code:
```
        for i := 0; i < 2; i++ {
                // ...
                p = i % 2 == 0 ? new(int, 42) : new(int, 43)
                // ...
        }
```
Since every reference-counted function result is stored in a temporary local variable to prevent its premature death, the actually executed pseudocode is like this:
```
        for i := 0; i < 2; i++ {
                // ...
                p = i % 2 == 0 ? {__temp0 = new(int, 42); __temp0} : {__temp1 = new(int, 43); __temp1}
                // ...
                decref(__temp0)
                decref(__temp1)
        }
```
This means that, e.g., `__temp0` will get some reference-counted value only once (at iteration 0), but have its reference count decremented twice (at iterations 0 and 1). It may cause a dangling pointer.

Notice that we cannot call `decref(__temp0)` immediately in the `{}` block, since `__temp0` must at least outlive the assignment to `p`.
