### ISSUE TITLE
Error making no sense

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#37]
I'm sorry for asking here, but since umka isn't that popular, I don't have any other option. I'm having an issue with an error, that doesn't make any sense at all. Here is the code:

```
type poly = int

// this line causes the issue:
fn newpoly*(x, y, vcount: int, v: []int): poly

fn (p: ^poly) setpos*(x, y: int) {
	cpolysetpos(x, y, p)
}

fn cpolysetpos(x, y: int, p: poly)

//fn (p ^poly) getpos*(): (int, int)
```

The error is: `Umka error umka/poly.um (6, 1): . expected but ; found`
 
What am I missing?

**Comment by vtereshkov** [comment]
@marekmaskarinec I think the problem is that an identifier name (probably, `poly`) coincides with the module name `poly`, so Umka is expecting something like `poly.foo()` but encounters just `poly`. Please rename either the identifier or the module. I admit this is a confusing error message, so let's keep the issue open.

**Comment by marekmaskarinec** [comment]
Thanks, now it works.
