### ISSUE TITLE
method not found even though method exists

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#42]
I have this function:
```
fn (i: ^img) scale*(x, y: real32) {
	imgsetscale(x, y, i^)
}
```

Then I have an image in entity struct like this:
```
type ent* = struct {
	p: polygon.poly
	image: image.img	
	color: uint32
	id: int32
}
```

But when I want to call the function, I get `Method scale is not found, structure expected to look for field`.

I call it like this:

```
	player := entity.mk(p, 0xff00ffff, 20)
	img := image.load("test.bmp")
	player.image = img

	player.image.scale(0.2, 0.2)
```

What am I doing wrong?

**Comment by vtereshkov** [comment]
@marekmaskarinec I suppose this is because of the type declaration `type img* = int`. Umka doesn't distinguish between declaring type aliases (`type T = S` in Go) and new types (`type T S`). When you declare `img`, it is just an alias of `int`, so Umka is searching for methods in the module where `int` is declared (the "universe" module) and in the current module (`game`), but not in `image`.

I agree that this is slightly inconsistent. As a workaround, I recommend that you construct a really new type for `img`, such as `type img* = struct{handle: int}`. Anyway, let's keep the issue open.

**Comment by vtereshkov** [comment]
Also fixed. Please check.
