### ISSUE TITLE
ifdef, or platform specific code

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#50]
I need to define some constants differently, when running on windows, than on linux. Is there a way to do this?

**Comment by vtereshkov** [comment]
@marekmaskarinec What constants do you mean?

**Comment by vtereshkov** [comment]
Umka does not and probably will never have a preprocessor or compile-time conditionals. On the other hand, I can implement the `getenv()` function to retrieve platform-specific environment variables. Some of them can be used to determine the OS type:

https://stackoverflow.com/questions/295052/how-can-i-determine-the-os-of-the-system-from-within-a-lua-script

In this case, you will have to define a global variable rather than a constant and initialize it according to the `getenv()` result. So would you like to have the `getenv()`?

**Comment by vtereshkov** [comment]
An alternative way is to have two Umka modules, `consts_windows.um` and `consts_linux.um`, and rename either the first or the second one into `consts.um` when building the release package. Other modules will just import this `consts.um`.

**Comment by vtereshkov** [comment]
I implemented `getenv()`, so you can now write something like this:
```
fn isLinux(): bool {return std.getenv("HOME") != ""}
```

**Comment by marekmaskarinec** [comment]
I will probably do that.

**Comment by vtereshkov** [comment]
Please close the issue when you are sure this approach works well.

**Comment by marekmaskarinec** [comment]
Could I get an updated build of `libumka` for windows? I currently don't have access to a windows machine to build it on.

**Comment by vtereshkov** [comment]
[umka_windows_mingw.zip](https://github.com/vtereshkov/umka-lang/files/6177774/umka_windows_mingw.zip)

**Comment by marekmaskarinec** [comment]
It doesn't seem to work. MinGW says: `skipping incompatible lib/windows/libumka.a when searching for -lumka`

**Comment by vtereshkov** [comment]
Have you replaced `lib/windows/libumka.a` with the new version contained in the archive?

**Comment by vtereshkov** [comment]
Hmm, I'm afraid I've given you a 32-bit version. Just a moment.

**Comment by marekmaskarinec** [comment]
Yes, I replaced it

**Comment by vtereshkov** [comment]
[umka_windows_mingw.zip](https://github.com/vtereshkov/umka-lang/files/6177911/umka_windows_mingw.zip)
Try this one. I even think `libumka.a` is unnecessary when linking dynamically. (I still don't know how to link it statically).

**Comment by marekmaskarinec** [comment]
It worked now.
