### ISSUE TITLE
Variable redeclaration warning/error

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#54]
This passes just fine for some reason:
```rust
var i: int

fn somefunc() {
  i := 2
}

fn main() {
  i = 3

  somefunc()

  printf("%d\n", i)
}
```

This will print out 3, but I think, it should return an warning. It can be really confusing.

**Comment by vtereshkov** [comment]
@marekmaskarinec I think this is a direct consequence of the conventional scope rules. The variable `i` in `somefunc` is local, while in `main` it is global. Does Go behave differently?

**Comment by marekmaskarinec** [comment]
To my suprise, go behaves the same, although I think it shouldn't. Redeclaration of a variable like this:
```go
i := 3
i := 2
```
causes an error like this: `no new variables on left side of :=` (in go).

The case shown earlier is a redeclaration of a variable too. On the other hand, I can see some use cases to a global variable not being forced. It think, this is a good case for a warning.

**Comment by vtereshkov** [comment]
Some languages like V disallow shadowing global variables with local ones, though most historically important languages, including C, allow this without a warning.

Moreover, warnings in interpreted languages are very rarely used, since they would be displayed again and again each time the user runs the program. It should be either an error or nothing.

**Comment by marekmaskarinec** [comment]
Ok. I can see some reasons, you would want to overwrite a global variable. I was just confused.
