### ISSUE TITLE
Struct values corruption

### ISSUE THREAD

**Issue by ProkopRandacek** [vtereshkov/umka-lang#57]
I'm passing 2 vector structs defined like this:
```
type (
    vec3* = struct {x, y, z: real32}
)
```
In a function defined like this:
```
fn CreateSphere *(pos, clr: vec3, rv, rd: real): int32
```
The call looks like this:
```
head := r8.CreateSphere(r8.vec3{0.1, 0.2, 0.3}, r8.vec3{0.4, 0.5, 0.6}, 0.7, 0.8)
```
The func bind in C:
```c
void umCreateSphere(UmkaStackSlot* p, UmkaStackSlot* r) {
        vec3* pos = (vec3*)&p[3];
        vec3* clr = (vec3*)&p[2];
        float rv  = (float) p[1].realVal;
        float rd  = (float) p[0].realVal;

        printf("%.1f, %.1f, %.1f, %.1f, %.1f, %.1f, %.1f, %.1f\n", pos->x, pos->y, pos->z, clr->x, clr->y, clr->z, rv, rd);

        int i = createSphere(*pos, *clr, rv, rd);

        r[0].intVal = i;
}
```
C vector struct definition:
```c
typedef struct {
        float x, y, z;
} vec3;
```
I would expect the printf to output to be `0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8`  
but the output is `0.6, 0.0, 0.1, 0.4, 0.5, 0.6, 0.7, 0.8`  
Only the position vector gets corrupted.

The code is from [here](https://github.com/ProkopRandacek/r8/tree/9d87afbca6f71f6fc49c41f2b4359306bad27b76)
`src/umka/bindings.c`, `src/vector.h`, `scripts/game.um`, `scripts/r8/r8.um`

**Comment by vtereshkov** [comment]
@ProkopRandacek The problem is that you pass `pos` and `clr` to `CreateSphere()` _by value_. This means that the structures are copied to the parameter stack. Each of them occupies more than one stack slot, so that `pos` will not be at `p[3]`.

If passing by value is absolutely necessary, you have to take into account the actual number of slots (for example, use `p[4]`, since a structure of three `float`s would probably occupy two 64-bit slots). But I would recommend passing by reference, i. e.

```
fn CreateSphere *(pos, clr: ^vec3, rv, rd: real): int32
r8.CreateSphere(&r8.vec3{0.1, 0.2, 0.3}, &r8.vec3{0.4, 0.5, 0.6}, 0.7, 0.8)
```

**Comment by ProkopRandacek** [comment]
Oh ok. Thanks for the description.
