### ISSUE TITLE
UmkaApi: parameters are not passed, when return type is [][]str

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#66]
I have this function:

```c
void umparsecsv(UmkaStackSlot *p, UmkaStackSlot *r) {
    char *inp = (char *)p[0].ptrVal;
    csv_t res;

    printf("%s\n", inp); // this doesn't print anything

    csvparse(&res, inp);

    free(res.collumns);

    r[0].ptrVal = (intptr_t)res.data;
}
```

This is the umka function:

```rust
fn ccsvparse(inp: str): [][]str

fn parse*(inp: str): [][]str {
    printf(inp)
    cval := ccsvparse(inp)

    return cval
}
```

If I run it, it printf the value normally in umka, but in c it doesn't work. Interesting is that if I set the return type to string, it prints the input even in c. Is it even possible to return a 2d array from c?

**Comment by vtereshkov** [comment]
Using dynamic arrays (even one-dimensional) for C/Umka data exchange is almost impossible. A dynamic array (as opposed to a static one) is a complex data structure that contains a header and a pointer to data. This pointer must always be allocated by Umka in order to be properly deallocated later. The only safe way to pass a dynamic array is what you successfully did before: instead of passing `arr` you used `&arr[0]` and `len(arr)`, which means using an existing pointer to data, not the dynamic array itself. And there is no safe way to return a dynamic array from C. You have to allocate and fill it in Umka using data returned from C.

Further, when an Umka function returns any structured value (array or structure), it allocates a hidden rightmost parameter, which is used as a pointer to the result. I told you how to work with structured results when talking about returning an `(int, int)` pair. So when the returned type is a structured type, the `inp` is not at `p[0]`.

**Comment by marekmaskarinec** [comment]
I see. I will probably make the csv parser in umka, since the benefits of it being in c are too low for it being worth the hassle. Should I close this?
