### ISSUE TITLE
Proposal: move the builtin I/O functions into an optional module

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#97]
Currently applications that use ```libumka``` cannot forbid the use of any of the builtin functions, including the I/O ones (```printf, scanf, rtlfopen, rtlfclose, rtlfseek, rtlftell, rtlfread, rtlfwrite, etc.```).

It is very easy to imagine applications that don't want to give file system access to their scripts. And if they did, they could easily write their own extension functions.

Also, instead of ```printf``` printing to ```stdout```, it might be desirable to have it print to the screen, or in-game console, or something.

**Comment by vtereshkov** [comment]
The built-in I/O functions like `printf()` and `scanf()` do not obey the conventional rules for functions since they are variadic. Thus, they have to be implemented as a core language feature. I can imagine incorporating them into a pseudo-module like `System` in Pascal, which is not a module in the proper sense. However, it would be an artificial decision.
